apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        echo "Cleaning workspace..."

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nose
spec:
  steps:
    - name: nose-test
      image: python:3.10
      script: |
        pip install pytest
        pytest -q
